//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockbase.Plugin.Instances.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blockbase.Plugin.Instances.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to andrepaixaao/blockbase.
        /// </summary>
        internal static string BLOCKBASE_IMAGE_PATH {
            get {
                return ResourceManager.GetString("BLOCKBASE_IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  &quot;kind&quot;: &quot;compute#instance&quot; ,  &quot;zone&quot;: &quot;projects/blockbase/zones/us-central1-a&quot;,  &quot;machineType&quot;: &quot;projects/blockbase/zones/us-central1-a/machineTypes/e2-medium&quot;,  &quot;displayDevice&quot;: {    &quot;enableDisplay&quot;: false  },  &quot;metadata&quot;: {    &quot;kind&quot;: &quot;compute#metadata&quot;,    &quot;items&quot;: []  },  &quot;tags&quot;: {    &quot;items&quot;: [      &quot;http-server&quot;,      &quot;https-server&quot;    ]  },  &quot;disks&quot;: [    {      &quot;kind&quot;: &quot;compute#attachedDisk&quot;,      &quot;type&quot;: &quot;PERSISTENT&quot;,      &quot;boot&quot;: true,      &quot;mode&quot;: &quot;READ_WRITE&quot;,      &quot;autoDelete&quot;: true,      &quot;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GOOGLE_REQUEST_BODY {
            get {
                return ResourceManager.GetString("GOOGLE_REQUEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to andrepaixaao/mongo.
        /// </summary>
        internal static string MONGO_IMAGE_PATH {
            get {
                return ResourceManager.GetString("MONGO_IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to andrepaixaao/postgres.
        /// </summary>
        internal static string POSTGRES_IMAGE_PATH {
            get {
                return ResourceManager.GetString("POSTGRES_IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yourpassword.
        /// </summary>
        internal static string POSTGRES_PASSWORD {
            get {
                return ResourceManager.GetString("POSTGRES_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postgres.
        /// </summary>
        internal static string POSTGRES_USER {
            get {
                return ResourceManager.GetString("POSTGRES_USER", resourceCulture);
            }
        }
    }
}
